-- Update the assets table to make asset_code optional for inserts
-- This is needed because the asset_code is auto-generated by a trigger
ALTER TABLE public.assets ALTER COLUMN asset_code DROP NOT NULL;

-- Add a trigger to ensure asset_code is always set before insert
CREATE OR REPLACE FUNCTION public.ensure_asset_code()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.asset_code IS NULL OR NEW.asset_code = '' THEN
    NEW.asset_code := generate_asset_code();
  END IF;
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create the trigger if it doesn't exist
DROP TRIGGER IF EXISTS ensure_asset_code_trigger ON public.assets;
CREATE TRIGGER ensure_asset_code_trigger
  BEFORE INSERT OR UPDATE ON public.assets
  FOR EACH ROW
  EXECUTE FUNCTION public.ensure_asset_code();